#!/bin/bash
# some more ls aliases
alias ll='ls -lh --color=auto'
alias la='ls -lah --color=auto'
alias l='ls -CF --color=auto'

# other fun aliases
alias sd="sudo"
alias pls='sd $(fc -ln -1)'
alias cls="clear"
alias gs="git status"
alias gc="git checkout"
alias gp="git fetch && git pull"

# for esp-idf
# alias idf=". $HOME/esp/v5.2/export.sh"

# tailscale
alias tailip="tailscale ip"
alias tailstat="tailscale status | grep "

# ollama
alias run-ollama="docker run --rm -d --gpus=all -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama"

